export enum ExpenseTypes {
    Food = 'food',
    Place = 'place',
    Decor = 'decor',
    Flowers = 'flowers',
    Photos = 'photos',
    Music = 'music',
    Entertainment = 'entertainment',
    Gifts = 'gifts',
    Dress = 'dress',
    Appearance = 'appearance',
    Accessories = 'accessories',
    Rings = 'rings',
    Accommodation = 'accommodation',
    Law = 'law',
    Transport = 'transport',
    Other = 'other',
}
