export enum Colors {
    PinkLight = '#ffe5ec',
    PinkLighter = '#ffc2d1',
    PinkLightest = '#ffb3c6',
    Pink = '#ff8fab',
    PinkDark = '#fb6f92',
    White = '#ffffff',
    LightGray = '#e0e0e0',
    Black = '#000000',
    LightBlue = '#91bee8',
    LightGreen = '#96d5a9',
    LightPurple = '#9a95c4',
    Yellow = '#fbbc05',
    BananaGold = '#f4d16e',
}
