export enum Colors {
    PinkLight = '#ffe5ec',
    PinkLighter = '#ffc2d1',
    PinkLightest = '#ffb3c6',
    Pink = '#ff8fab',
    PinkDark = '#fb6f92',
    Mango = '#FBBC05',
    Yellow = '#ffff00',
    TurquoiseLight = '#91D5C9',
    asd = '#91BEE8',
    White = '#ffffff',
    WhiteDark = '#aaaaaa',
    BlackLight = '#555555',
    Black = '#000000',
    LightBlue = '#91bee8',
    LightGreen = '#91d5c9',
    LightPurple = '#9a95c4',
    LightGray = '#e0e0e0',
    Gray = '#cccccc',
    GrayOut = '#00000070',
    StatusCreated = '#dadada',
    StatusInvited = '#f6d36f',
    StatusAccepted = '#b6d79d',
    StatusRejected = '#ed6055',
}
